export const VERSIONS = [
  { version: "v0.1", hours: 0, note: "CLI skeleton, language pick, basic settings" },
  { version: "v0.1.1", hours: 1, note: "first-run flow and log toggle" },
  { version: "v0.1.2", hours: 1, note: "prompt and colours" },
  { version: "v0.2", hours: 1, note: "get and listf" },
  { version: "v0.3", hours: 1.5, note: "pull and upload framework" },
  { version: "v1.0", hours: 2, note: "TUI main screen and sign-in" },
  { version: "v1.0.1", hours: 1, note: "TUI settings page" },
  { version: "v1.0.3", hours: 1, note: "TUI messages and profile" },
  { version: "v1.0.4", hours: 1, note: "task queue persistence" },
  { version: "v1.1", hours: 1, note: "chunked storage engine" },
  { version: "v1.1.3", hours: 1, note: "file.json manifest merge" },
  { version: "v1.1.6", hours: 1, note: "automatic repo expansion" },
  { version: "v1.1.10", hours: 1, note: "downloader and hash check" },
  { version: "v1.1.14", hours: 1, note: "uploader and speed limit" },
  { version: "v1.1.20", hours: 2, note: "resume and priority" },
  { version: "v1.2", hours: 2, note: "64M parameter search model" },
  { version: "v1.2.2", hours: 1, note: "CDN links and sharing" },
  { version: "v1.2.5", hours: 2, note: "recycle bin and rollback" },
  { version: "v1.3", hours: 3, note: "installer and self-repair" },
];
